from ctypes import *

class SmartHeader(Structure):
    _pack_ = 1
    _fields_ = [('Signature', c_ubyte * 3),	
                ('HW_Version', c_ubyte * 16),
                ('FW_Version', c_ubyte * 16),
                ('FlashType', c_ubyte),	
                ('FlashID', c_ubyte * 6),
                ('FlashPECycle', c_uint32),		
                ('TotalVBCountWithHash', c_uint32),		
                ('InitialBadBlockCount', c_uint16),		
                ('LaterBadBlockCount', c_uint16),		
                ('SpareBlockCount', c_uint16),		
                ('ECCNumber', c_ubyte),		
                ('TotalEraseCount', c_uint32),		
                ('AbnormalShutDownCount', c_uint32),		
                ('PowerCycleCount', c_uint32),		
                ('SMART_TransferCnt', c_ubyte),		
                ('SMART_Info_Type', c_ubyte),		
                ('TotalCECount', c_ubyte),		
                ('PlanesPerVPage', 	c_ubyte),		
                ('PrepareBusy', c_ubyte),		
                ('MPVersion', c_uint16 * 2),
                ('TotalVBCountOfFlash', c_uint32),
                ('VB_GapOffset', c_uint16),
                ('VB_GapNumber', c_uint16),
                ('WriteCnt', c_uint32),		
                ('TempWriteCnt', c_uint16),	
                ('ReadCntVBNum', c_uint16),
                ('SMART_TransferCnt_GRC', c_ubyte),
                ('SD_CID', c_ubyte * 16),		
                ('SD_CSD', c_ubyte * 14),		
                ('SD_CSD_Bit15_8', c_ubyte),		
                ('SD_CSD_crc', c_ubyte),		
                ('SD_SCR ', c_ubyte * 8),
                ('WritableOnceFlag', c_ubyte),		
                ('CMD42Lock', c_ubyte),		
                ('FirmwareLock', c_ubyte),		
                ('SMART_TransferCnt4LS', c_uint16),
                ('MinEraseCnt', c_uint16),
                ('MaxEraseCnt', c_uint16),
                ('EraseCountOffset', c_uint16),
                ('SmartInfoFileLBA', c_uint32),
                ('SmartInfoFileSize', c_uint16),
                ('Reserved', c_ubyte * 357),
                ('PackageVersion', c_ubyte),	
                ('HeaderVersion', c_ubyte),		
                ('CheckSum', c_ubyte)]